### ISSUE TITLE
RATS is flaky in parallel due to --random-port

### ISSUE THREAD

**Issue by charleshansen** [cloudfoundry/routing-acceptance-tests#8]
There is a race condition in cloud controller where multiple calls to `cf create-route` with `--random-port` may pick the same random port and cause errors https://github.com/cloudfoundry/cloud_controller_ng/issues/1050 

RATS uses `--random-port` heavily and will sometimes fail when run in parallel. 

The bug in cloud_controller is very difficult to fix and has not affected many actual cloud foundry users and will not be prioritized. To make RATS run in parallel, it would be good not to rely on `--random-route`. 

For some alternative approaches, look at https://github.com/cloudfoundry/gorouter/blob/6734f35425ce1525660f7b231e030f2660eaf668/test_util/ports.go#L15
The actual solution will be more complicated because you will need to consider the router group port range instead of the ephemeral port range.

**Comment by charleshansen** [comment]
We did mitigate the problem in 35762b9d3af6c63c474ef7bdb3a81c4c5997d00b, maybe this isn't that important

**Comment by shubhaat** [comment]
@aaronshurley - can you look at this and recommend next steps.

**Comment by KauzClay** [comment]
@charleshansen sounds like the mitigation works, so we will close this. Feel free to reopen it if the problem persists.
